# -*- coding: utf-8 -*-
"""APL_Logistics_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zbEEUkVcnlBLPHUh8OTqlWqvfYsvk2pT

# 🚢 APL Logistics — Customer, Product & Profitability Analysis

## ⚙️ Cell 1 — Install Libraries
"""

!pip install -q plotly kaleido
print("✅ Done")

"""## 📦 Cell 2 — Import All Libraries"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import warnings
warnings.filterwarnings("ignore")

plt.rcParams.update({
    "figure.facecolor": "white",
    "axes.facecolor": "#f8f9fa",
    "axes.grid": True,
    "grid.alpha": 0.4,
    "font.size": 11
})
PALETTE = ["#1a6faf", "#22c55e", "#ef4444", "#f59e0b", "#7c3aed", "#0891b2"]
print("✅ All libraries imported successfully")

"""## 📁 Cell 3 — Mount Google Drive & Load Data"""

from google.colab import drive
drive.mount('/content/drive')

FILE_PATH = '/content/drive/MyDrive/APL_Logistics.csv'

df = pd.read_csv(FILE_PATH, encoding='latin1', low_memory=False)
print(f"✅ Data loaded: {df.shape[0]:,} rows × {df.shape[1]} columns")

"""## 🔍 Cell 4 — Data Overview"""

print("=" * 55)
print("DATASET OVERVIEW")
print("=" * 55)
print(f"Shape : {df.shape}")
print(f"Columns: {df.shape[1]}")
print()
print("── Column Data Types ──")
print(df.dtypes)
print()
print("── Missing Values ──")
missing = df.isnull().sum()
print(missing[missing > 0] if missing[missing > 0].any() else "No missing values found ✅")
print()
display(df.head(3))

"""## 🧹 Cell 5 — Data Cleaning & Feature Engineering"""

print("=" * 55)
print("STEP: DATA CLEANING & FINANCIAL VALIDATION")
print("=" * 55)

# Coerce numeric columns
num_cols = [
    'Benefit per order', 'Sales per customer', 'Order Item Discount',
    'Order Item Discount Rate', 'Order Item Product Price',
    'Order Item Profit Ratio', 'Order Item Quantity', 'Sales',
    'Order Item Total', 'Order Profit Per Order'
]
for c in num_cols:
    if c in df.columns:
        df[c] = pd.to_numeric(df[c], errors='coerce')

# Drop rows where both Sales and Profit are null
before = len(df)
df.dropna(subset=['Sales', 'Order Profit Per Order'], how='all', inplace=True)
print(f"Dropped {before - len(df)} invalid rows. Remaining: {len(df):,}")

# Derived columns
df['Profit Margin %']  = (df['Order Profit Per Order'] / df['Sales'].replace(0, np.nan)) * 100
df['Customer Name']    = df['Customer Fname'].astype(str) + ' ' + df['Customer Lname'].astype(str)
df['Is Loss Order']    = (df['Order Profit Per Order'] < 0).astype(int)
df['Discount Bracket'] = pd.cut(
    df['Order Item Discount Rate'],
    bins=[-0.01, 0.0, 0.05, 0.10, 0.15, 0.20, 0.30, 1.0],
    labels=['0%', '1-5%', '5-10%', '10-15%', '15-20%', '20-30%', '30%+']
)

print("\n✅ Derived columns added:")
print("   Profit Margin % | Customer Name | Is Loss Order | Discount Bracket")
display(df[['Sales', 'Order Profit Per Order', 'Profit Margin %', 'Is Loss Order', 'Discount Bracket']].head())

"""## 📊 Cell 6 — KPI Summary"""

total_revenue = df['Sales'].sum()
total_profit  = df['Order Profit Per Order'].sum()
total_orders  = len(df)
avg_margin    = (total_profit / total_revenue) * 100
loss_orders   = df['Is Loss Order'].sum()
loss_pct      = loss_orders / total_orders * 100
avg_order_val = total_revenue / total_orders
unique_custs  = df['Customer Id'].nunique()

print("=" * 50)
print("        KEY PERFORMANCE INDICATORS")
print("=" * 50)
print(f"  Total Revenue         : ${total_revenue:>15,.2f}")
print(f"  Total Profit          : ${total_profit:>15,.2f}")
print(f"  Profit Margin         : {avg_margin:>15.2f} %")
print(f"  Total Orders          : {total_orders:>15,}")
print(f"  Avg Order Value       : ${avg_order_val:>15,.2f}")
print(f"  Loss-Making Orders    : {loss_orders:>15,}  ({loss_pct:.1f}%)")
print(f"  Unique Customers      : {unique_custs:>15,}")
print(f"  Avg Discount Rate     : {df['Order Item Discount Rate'].mean()*100:>15.2f} %")
print(f"  Total Discount Given  : ${df['Order Item Discount'].sum():>15,.2f}")
print("=" * 50)

"""## 📈 Cell 7 — Revenue & Profit by Customer Segment"""

seg = df.groupby('Customer Segment').agg(
    Revenue=('Sales', 'sum'),
    Profit=('Order Profit Per Order', 'sum'),
    Orders=('Sales', 'count')
).assign(Margin=lambda x: (x['Profit'] / x['Revenue'] * 100).round(1))

print(seg.round(2))

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('Revenue & Profit by Customer Segment', fontsize=14, fontweight='bold')

seg[['Revenue', 'Profit']].plot(kind='bar', ax=axes[0],
    color=['#1a6faf', '#22c55e'], edgecolor='none', width=0.6)
axes[0].set_title('Revenue vs Profit')
axes[0].set_ylabel('Amount ($)')
axes[0].tick_params(axis='x', rotation=0)
axes[0].yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'${x:,.0f}'))

seg['Margin'].plot(kind='bar', ax=axes[1], color='#f59e0b', edgecolor='none', width=0.6)
axes[1].axhline(0, color='red', linestyle='--', linewidth=1)
axes[1].set_title('Profit Margin %')
axes[1].set_ylabel('Margin %')
axes[1].tick_params(axis='x', rotation=0)

plt.tight_layout()
plt.savefig('chart_01_segment.png', dpi=150, bbox_inches='tight')
plt.show()
print('📊 Saved: chart_01_segment.png')

"""## 📉 Cell 8 — Profit Distribution Histogram"""

fig, ax = plt.subplots(figsize=(11, 4))
ax.hist(df['Order Profit Per Order'].clip(-500, 500), bins=80,
        color='#1a6faf', edgecolor='none', alpha=0.85)
ax.axvline(0, color='red', linestyle='--', linewidth=1.5, label='Break-even (0)')
ax.set_title('Distribution of Profit Per Order', fontsize=13, fontweight='bold')
ax.set_xlabel('Profit Per Order ($)')
ax.set_ylabel('Number of Orders')
ax.legend()
plt.tight_layout()
plt.savefig('chart_02_profit_dist.png', dpi=150, bbox_inches='tight')
plt.show()

print(f"Orders with profit > 0  : {(df['Order Profit Per Order'] > 0).sum():,}")
print(f"Orders with profit = 0  : {(df['Order Profit Per Order'] == 0).sum():,}")
print(f"Orders with profit < 0  : {(df['Order Profit Per Order'] < 0).sum():,}  ← Loss orders")
print('📊 Saved: chart_02_profit_dist.png')

"""## 📦 Cell 9 — Category-Level Profitability"""

cat_grp = df.groupby('Category Name').agg(
    Revenue=('Sales', 'sum'),
    Profit=('Order Profit Per Order', 'sum'),
    Orders=('Sales', 'count'),
    Avg_Discount=('Order Item Discount Rate', 'mean')
).assign(Margin=lambda x: (x['Profit'] / x['Revenue'] * 100).round(1)).sort_values('Profit')

print('--- Category Profitability ---')
print(cat_grp.round(2))

loss_cats = cat_grp[cat_grp['Profit'] < 0]
if not loss_cats.empty:
    print(f"\n⚠️ Loss-Making Categories ({len(loss_cats)}):")
    print(loss_cats[['Revenue', 'Profit', 'Margin']])
else:
    print("\n✅ No loss-making categories.")

fig, ax = plt.subplots(figsize=(12, 7))
colors = ['#ef4444' if p < 0 else '#1a6faf' for p in cat_grp['Profit']]
cat_grp['Profit'].plot(kind='barh', ax=ax, color=colors, edgecolor='none')
ax.axvline(0, color='black', linewidth=0.8)
ax.set_title('Total Profit by Category  (Red = Loss)', fontsize=13, fontweight='bold')
ax.set_xlabel('Total Profit ($)')
plt.tight_layout()
plt.savefig('chart_03_category_profit.png', dpi=150, bbox_inches='tight')
plt.show()
print('📊 Saved: chart_03_category_profit.png')

"""## 🔥 Cell 10 — Category × Segment Profit Heatmap"""

heat = df.pivot_table(index='Category Name', columns='Customer Segment',
                      values='Order Profit Per Order', aggfunc='sum')

fig, ax = plt.subplots(figsize=(10, 8))
sns.heatmap(heat, cmap='RdYlGn', annot=True, fmt='.0f',
            linewidths=0.5, ax=ax, cbar_kws={'label': 'Profit ($)'})
ax.set_title('Profit Heatmap: Category × Customer Segment', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('chart_04_heatmap_cat_seg.png', dpi=150, bbox_inches='tight')
plt.show()
print('📊 Saved: chart_04_heatmap_cat_seg.png')

"""## 🏆 Cell 11 — Top & Bottom Products"""

prod_grp = df.groupby('Product Name').agg(
    Revenue=('Sales', 'sum'),
    Profit=('Order Profit Per Order', 'sum'),
    Orders=('Sales', 'count')
).assign(Margin=lambda x: (x['Profit'] / x['Revenue'] * 100).round(1))

top15  = prod_grp.nlargest(15, 'Profit')
bot15  = prod_grp.nsmallest(15, 'Profit')
risky  = prod_grp[
    (prod_grp['Revenue'] > prod_grp['Revenue'].quantile(0.5)) &
    (prod_grp['Margin'] < 10)
].nlargest(10, 'Revenue')

print('--- Top 10 Most Profitable Products ---')
print(top15.head(10)[['Revenue', 'Profit', 'Margin']])

print('\n--- Top 10 Loss-Making Products ---')
print(bot15.head(10)[['Revenue', 'Profit', 'Margin']])

print('\n--- ⚠️ High Revenue, Low Margin Products ---')
print(risky[['Revenue', 'Profit', 'Margin']])

fig, axes = plt.subplots(1, 2, figsize=(16, 7))

axes[0].barh(top15['Profit'].index, top15['Profit'].values, color='#1a6faf', edgecolor='none')
axes[0].set_title('Top 15 Products by Profit', fontsize=12, fontweight='bold')
axes[0].set_xlabel('Profit ($)')
axes[0].invert_yaxis()

axes[1].barh(bot15['Profit'].index, bot15['Profit'].values, color='#ef4444', edgecolor='none')
axes[1].set_title('Bottom 15 Products (Loss)', fontsize=12, fontweight='bold')
axes[1].set_xlabel('Profit ($)')
axes[1].axvline(0, color='black', linewidth=0.8)
axes[1].invert_yaxis()

plt.tight_layout()
plt.savefig('chart_05_products.png', dpi=150, bbox_inches='tight')
plt.show()
print('📊 Saved: chart_05_products.png')

"""## 👥 Cell 12 — Customer Value Analysis"""

cust_grp = df.groupby(['Customer Id', 'Customer Name', 'Customer Segment']).agg(
    Revenue=('Sales', 'sum'),
    Profit=('Order Profit Per Order', 'sum'),
    Orders=('Sales', 'count')
).assign(Margin=lambda x: (x['Profit'] / x['Revenue'] * 100).round(1)).reset_index()

print(f"Total unique customers : {len(cust_grp):,}")
print(f"Avg profit per customer: ${cust_grp['Profit'].mean():,.2f}")
print(f"Loss-making customers  : {(cust_grp['Profit'] < 0).sum():,}")

# Pareto
cust_sorted = cust_grp.sort_values('Profit', ascending=False).reset_index(drop=True)
cust_sorted['Cum Profit %']   = cust_sorted['Profit'].cumsum() / cust_sorted['Profit'].sum() * 100
cust_sorted['Cum Customer %'] = np.arange(1, len(cust_sorted)+1) / len(cust_sorted) * 100
top20_pct = cust_sorted[cust_sorted['Cum Customer %'] <= 20]['Profit'].sum() / cust_sorted['Profit'].sum() * 100
print(f"\n📌 Pareto: Top 20% customers → {top20_pct:.1f}% of total profit")

fig, axes = plt.subplots(1, 2, figsize=(15, 5))

top15c = cust_sorted.head(15)
axes[0].barh(top15c['Customer Name'], top15c['Profit'], color='#1a6faf', edgecolor='none')
axes[0].set_title('Top 15 Customers by Profit', fontsize=12, fontweight='bold')
axes[0].set_xlabel('Profit ($)')
axes[0].invert_yaxis()

axes[1].plot(cust_sorted['Cum Customer %'], cust_sorted['Cum Profit %'], color='#1a6faf', linewidth=2)
axes[1].axvline(20, color='red', linestyle='--', label='Top 20% customers')
axes[1].axhline(top20_pct, color='orange', linestyle='--', label=f'{top20_pct:.1f}% profit')
axes[1].set_title('Customer Profit Pareto Curve', fontsize=12, fontweight='bold')
axes[1].set_xlabel('Cumulative Customers %')
axes[1].set_ylabel('Cumulative Profit %')
axes[1].legend()

plt.tight_layout()
plt.savefig('chart_06_customer_value.png', dpi=150, bbox_inches='tight')
plt.show()
print('📊 Saved: chart_06_customer_value.png')

"""## 🏷️ Cell 13 — Discount Impact Analysis"""

disc_impact = df.groupby('Discount Bracket', observed=True).agg(
    Avg_Margin=('Profit Margin %', 'mean'),
    Avg_Profit_Ratio=('Order Item Profit Ratio', 'mean'),
    Orders=('Sales', 'count'),
    Total_Profit=('Order Profit Per Order', 'sum'),
    Total_Discount=('Order Item Discount', 'sum')
).round(2)

print('--- Profitability by Discount Bracket ---')
print(disc_impact)

corr = df[['Order Item Discount Rate', 'Order Item Profit Ratio',
           'Order Profit Per Order', 'Profit Margin %']].corr()
print('\n--- Correlation: Discount Rate vs Profit ---')
print(corr.round(3))

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

colors = ['#ef4444' if v < 0 else '#22c55e' for v in disc_impact['Avg_Margin']]
disc_impact['Avg_Margin'].plot(kind='bar', ax=axes[0], color=colors, edgecolor='none')
axes[0].axhline(0, color='black', linewidth=0.8)
axes[0].set_title('Avg Profit Margin % by Discount Bracket', fontsize=12, fontweight='bold')
axes[0].set_ylabel('Avg Margin %')
axes[0].tick_params(axis='x', rotation=30)

sample = df.sample(min(3000, len(df)), random_state=42)
axes[1].scatter(sample['Order Item Discount Rate'], sample['Order Item Profit Ratio'],
                alpha=0.25, color='#1a6faf', s=8)
axes[1].axhline(0, color='red', linestyle='--', linewidth=1.2)
axes[1].set_title('Discount Rate vs Profit Ratio', fontsize=12, fontweight='bold')
axes[1].set_xlabel('Discount Rate')
axes[1].set_ylabel('Profit Ratio')

plt.tight_layout()
plt.savefig('chart_07_discount_impact.png', dpi=150, bbox_inches='tight')
plt.show()
print('📊 Saved: chart_07_discount_impact.png')

"""## 🌍 Cell 14 — Market & Regional Analysis"""

market_grp = df.groupby('Market').agg(
    Revenue=('Sales', 'sum'),
    Profit=('Order Profit Per Order', 'sum'),
    Orders=('Sales', 'count')
).assign(Margin=lambda x: (x['Profit'] / x['Revenue'] * 100).round(1)).sort_values('Profit', ascending=False)

region_grp = df.groupby('Order Region').agg(
    Revenue=('Sales', 'sum'),
    Profit=('Order Profit Per Order', 'sum'),
    Orders=('Sales', 'count')
).assign(Margin=lambda x: (x['Profit'] / x['Revenue'] * 100).round(1)).sort_values('Profit', ascending=False)

print('--- Market-Level Profitability ---')
print(market_grp.round(2))

print('\n--- Top 10 Regions by Profit ---')
print(region_grp.head(10).round(2))

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

market_grp[['Revenue', 'Profit']].plot(kind='bar', ax=axes[0],
    color=['#1a6faf', '#22c55e'], edgecolor='none')
axes[0].set_title('Revenue vs Profit by Market', fontsize=12, fontweight='bold')
axes[0].tick_params(axis='x', rotation=30)

top_reg = region_grp.head(10)['Margin'].sort_values()
bar_colors = ['#ef4444' if v < 0 else '#1a6faf' for v in top_reg]
top_reg.plot(kind='barh', ax=axes[1], color=bar_colors, edgecolor='none')
axes[1].axvline(0, color='black', linewidth=0.8)
axes[1].set_title('Margin % — Top 10 Regions', fontsize=12, fontweight='bold')

plt.tight_layout()
plt.savefig('chart_08_market_region.png', dpi=150, bbox_inches='tight')
plt.show()
print('📊 Saved: chart_08_market_region.png')

"""## 🗺️ Cell 15 — Region × Category Heatmap"""

rc_heat = df.pivot_table(index='Order Region', columns='Category Name',
                          values='Order Profit Per Order', aggfunc='sum')

fig, ax = plt.subplots(figsize=(18, 8))
sns.heatmap(rc_heat, cmap='RdYlGn', annot=False, linewidths=0.3,
            ax=ax, cbar_kws={'label': 'Profit ($)'})
ax.set_title('Profit Heatmap: Region × Category', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('chart_09_region_category_heatmap.png', dpi=150, bbox_inches='tight')
plt.show()
print('📊 Saved: chart_09_region_category_heatmap.png')

"""## 💾 Cell 16 — Export All Summary CSVs"""

cat_grp.reset_index().to_csv('category_profitability.csv', index=False)
prod_grp.reset_index().to_csv('product_profitability.csv', index=False)
cust_grp.to_csv('customer_profitability.csv', index=False)
market_grp.reset_index().to_csv('market_profitability.csv', index=False)
region_grp.reset_index().to_csv('region_profitability.csv', index=False)
disc_impact.reset_index().to_csv('discount_impact.csv', index=False)

# KPI summary
kpi_df = pd.DataFrame({
    'KPI': [
        'Total Revenue ($)', 'Total Profit ($)', 'Profit Margin (%)',
        'Total Orders', 'Avg Order Value ($)', 'Loss-Making Orders',
        'Loss-Making Orders (%)', 'Unique Customers',
        'Total Discount Given ($)', 'Avg Discount Rate (%)'
    ],
    'Value': [
        f"${df['Sales'].sum():,.2f}",
        f"${df['Order Profit Per Order'].sum():,.2f}",
        f"{df['Order Profit Per Order'].sum()/df['Sales'].sum()*100:.2f}%",
        f"{len(df):,}",
        f"${df['Sales'].sum()/len(df):,.2f}",
        f"{df['Is Loss Order'].sum():,}",
        f"{df['Is Loss Order'].mean()*100:.1f}%",
        f"{df['Customer Id'].nunique():,}",
        f"${df['Order Item Discount'].sum():,.2f}",
        f"{df['Order Item Discount Rate'].mean()*100:.2f}%"
    ]
})
kpi_df.to_csv('kpi_summary.csv', index=False)

print('✅ All files exported:')
for f in ['kpi_summary.csv','category_profitability.csv','product_profitability.csv',
          'customer_profitability.csv','market_profitability.csv',
          'region_profitability.csv','discount_impact.csv']:
    print(f'   📄 {f}')
print('\n✅ All charts saved:')
for i in range(1, 10):
    print(f'   🖼️  chart_0{i}_*.png')

"""## ✅ Cell 17 — Download All Outputs (Optional)
Run this cell to zip and download everything to your computer.
"""

import zipfile, os
from google.colab import files

output_files = [f for f in os.listdir() if f.endswith(('.png', '.csv'))]

with zipfile.ZipFile('APL_Outputs.zip', 'w') as zf:
    for f in output_files:
        zf.write(f)

print(f'✅ Zipped {len(output_files)} files into APL_Outputs.zip')
files.download('APL_Outputs.zip')  # Auto-downloads to your computer